package com.se.onprem.util;

public interface ConstantSolrFields
{
	String PL_NAME = "plName";
	String PL_ID = "PL_ID";
	String TAX_PL_NAME = "PLNAME";
	String SOLR_TAXONOMY_CORENAME = "para.solr.taxonomyCoreName";

	String TAX_PL_TYPE_NAME = "TYPENAME";
	String TAX_MAIN_NAME = "MAINNAME";
	String TAX_MAIN_ID = "MAINID";
	String TAX_SUB_NAME = "SUBNAME";
	String TAX_SUB_ID = "SUBID";
	String TAX_PL_ID = "PLID";
	String TAX_SUBSEARCHABLE_FLAG = "SUBSEARCHABLEFLAG";
	String TAX_MAINSEARCHABLE_FLAG = "MAINSEARCHABLEFLAG";

	String TAX_FET_NAME = "FEATURENAME";
	String TAX_FET_DEFINITION = "FEATUREDEFINITION";
	String TAX_FET_HCOLNAME = "HCOLNAME";
	String TAX_FET_UNIT = "UNIT";
	String TAX_SORT_TYPE = "SORTTYPE";
	String TAX_FET_ID = "FETID";
	String TAX_SUB_EMBEDED_UI_ID = "SUBUIID";
	String TAX_MAIN_EMBEDED_UI_ID = "MAINUIID";
	String TAX_EMBEDED_UI_ID = "UIID";
	String TAX_DISPLAY_ORDER = "DISPLAYORDER";
	String TAX_SUB_CATEGORY_DISPLAY_ORDER = "SUB_CATEGORY_DISPLAY_ORDER";
	String TAX_MAIN_CATEGORY_DISPLAY_ORDER = "MAIN_CATEGORY_DISPLAY_ORDER";

	String NAN_PN = "NAN_PN";
	String PART_DESCRIPTION = "PART_DESCRIPTION";
	String MAN_NAME_TOKEN = "MAN_NAME_TOKEN";
	String INV_COUNT_ORIGINAL = "INV_COUNT_ORIGINAL";
	String FULL_PART = "FULL_PART";
	String MAN_NAME = "MAN_NAME";
	String LIFE_CYCLE = "LC_STATE";
	String STAR_RATING = "STAR_RATING";
	String ROHS = "ROHS";
	String VENDOR = "Manufacturer";
	String FOOTPRINT = "HAS_FOOTPRINT";
	String PART_STATUS = "PART_STATUS";
	String ROHS_VERSION = "ROHS_VERSION";
	String MAN_ID = "MAN_ID";
	String SMALL_IMAGE = "SMALL_IMAGE";
	String PART_ID = "componentId";
	String VALUE_ID = "VALUE_ID";

	String DATASHEET_ID = "PDF_ID";
	String LARGE_IMAGE = "LARGE_IMAGE";
	String DATASHEET_URL = "PDF_URL";

	String MAIN_CAT_IDS = "MAIN_CAT_IDS";
	String MAIN_CAT_NAMES = "MAIN_CAT_NAMES";
	String SUB_CAT_IDS = "SUB_CAT_IDS";
	String SUB_CAT_NAMES = "SUB_CAT_NAMES";

	String MAN_NAME_EXACT = "MAN_NAME_EXACT";
	String NAN_PARTNUM_EXACT = "NAN_PARTNUM_EXACT";

	String NAN_PARTNUM = "NAN_PARTNUM";

	String IS_CUSTOM_PART = "IS_CUSTOM";

	String PASSIVE_CORE_NAN_PARTNUM = "NAN_PARTNUM";
	String PASSIVE_CORE_MAN_NAME = "MAN_NAME";
	String PASSIVE_CORE_PART_NUMBER = "COM_PARTNUM";
	String PASSIVE_CORE_DESCRIPTION = "DESCRIPTION";
	String PASSIVE_CORE_PART_ID = "COM_ID";
	String MAN_ORDER = "MAN_ORDER";
	String TAX_PL_TYPE_SORT = "PL_TYPE_SORT";

	String MAIN_CAT_NAMES_TOKNIZD = "MAIN_CAT_NAMES_TOKNIZD";
	String SUB_CAT_NAMES_TOKNIZD = "SUB_CAT_NAMES_TOKNIZD";
	String COM_ID = "COM_ID";
	String DESCRIPTION = "ROW_COM_DESC";
	String IMAGE_URL = "IMAGE_URL";
	String CPN = "CPN";
	String MPN = "MPN";
	
}
